language: node_js
notifications:
  email: false
cache:
  directories:
    - node_modules
node_js: lts/*
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: commitlint
      script: npx @commitlint/travis-cli
    - stage: audit
      script: yarn audit
    - stage: release
      if: branch = master
      node_js: lts/*
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
